SELECT
    COUNT(*)        AS CNT,
    COALESCE(SUM(WLFE_DD_SETL_AMT), 0) AS ALL_SETL_AMT,
    COALESCE(SUM(WLFE_DD_CAN_AMT), 0) AS ALL_CAN_AMT,
    COALESCE(SUM(WLFE_DD_RFND), 0) AS ALL_RFND_AMT
FROM ENT_WLFE_SETL_DD_SM A
LEFT JOIN ENT_INTT_LGDR B ON A.USE_INTT_ID = B.USE_INTT_ID
WHERE 1=1
AND A.SM_DT BETWEEN '20250520' AND '202550523'